# Generated by Django 5.1.5 on 2025-02-07 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank='True', verbose_name='Дата')),
                ('agreement_date', models.DateField(verbose_name='Дата договора')),
                ('account_number', models.IntegerField(verbose_name='Номер счёта')),
                ('act_date', models.DateField(verbose_name='Дата акта')),
                ('summa', models.IntegerField(verbose_name='Сумма')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('contract_data', models.CharField(max_length=250, verbose_name='Данные контракта')),
                ('act_data', models.CharField(max_length=250, verbose_name='Данные акта')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.clients', verbose_name='Клиент')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.executors', verbose_name='Исполнитель')),
            ],
        ),
    ]
