# Generated by Django 5.1.5 on 2025-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_name', models.CharField(max_length=250, verbose_name='last_name')),
                ('first_name', models.CharField(max_length=250, verbose_name='name')),
                ('patronymic', models.CharField(max_length=250, verbose_name='patronymic')),
                ('legal_adress', models.CharField(max_length=250, verbose_name='legal_adress')),
                ('physical_adress', models.CharField(max_length=250, verbose_name='physical_adress')),
                ('inn', models.IntegerField()),
                ('kpp', models.IntegerField()),
                ('bank', models.IntegerField()),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateTimeField()),
                ('passports_series', models.IntegerField()),
                ('passports_number', models.IntegerField()),
                ('services', models.IntegerField()),
                ('user_state', models.IntegerField()),
            ],
        ),
    ]
