# Generated by Django 5.1.5 on 2025-02-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='legal_adress',
            field=models.CharField(max_length=250, verbose_name='Адресс прописки'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='patronymic',
            field=models.CharField(max_length=250, verbose_name='Отчетство'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='physical_adress',
            field=models.CharField(max_length=250, verbose_name='Фактический адресс'),
        ),
    ]
