# Generated by Django 5.1.5 on 2025-02-07 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('manager', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.services', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='user_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.status', verbose_name='Статус'),
        ),
    ]
