# Generated by Django 5.1.5 on 2025-02-07 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emolyees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=250, verbose_name='Отчетство')),
                ('login', models.CharField(max_length=250, verbose_name='Логин')),
                ('password', models.CharField(max_length=250, verbose_name='пароль')),
                ('legal_adress', models.CharField(max_length=250, verbose_name='Адресс прописки')),
                ('physical_adress', models.CharField(max_length=250, verbose_name='Фактический адресс')),
                ('inn', models.IntegerField()),
                ('snils', models.IntegerField()),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('passports_series', models.IntegerField(max_length=4)),
                ('passports_number', models.IntegerField(max_length=6)),
                ('date_of_employment', models.DateField(verbose_name='Дата принятия на работу')),
                ('date_of_dismissal', models.DateField(null=True, verbose_name='Дата увольнения')),
                ('education', models.CharField(max_length=250, verbose_name='Образование')),
                ('salary', models.IntegerField(verbose_name='Оклад')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.position', verbose_name='Должность')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.role', verbose_name='Роль')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.subdivision', verbose_name='Подразделение')),
            ],
        ),
    ]
