# Generated by Django 5.1.5 on 2025-02-08 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
        ('clients', '0002_alter_clients_services_alter_clients_user_state'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='phone',
            field=models.CharField(max_length=250, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.services', verbose_name='Услуга'),
        ),
    ]
