from django.db import models


class Emolyees(models.Model):
    date = models.DateField(auto_now_add=True)
    last_name = models.CharField(max_length=250, verbose_name='Фамилия')
    first_name = models.CharField(max_length=250, verbose_name='Имя')
    patronymic = models.CharField(max_length=250, verbose_name='Отчетство')
    login = models.CharField(max_length=250, verbose_name='Логин')
    password = models.CharField(max_length=250, verbose_name='пароль')
    legal_adress = models.CharField(max_length=250, verbose_name='Адресс прописки')
    physical_adress = models.CharField(max_length=250, verbose_name='Фактический адресс')
    position = models.CharField(max_length=250, verbose_name='Должность')
    subdivision =  models.CharField(max_length=250, verbose_name='Подразделение')
    role =  models.CharField(max_length=250, verbose_name='Роль')
    inn = models.IntegerField()
    snils = models.IntegerField()
    bank = models.IntegerField()
    phone = models.CharField(max_length=14)
    email = models.EmailField()
    date_of_birth = models.DateTimeField()
    passports_series = models.IntegerField()
    passports_number = models.IntegerField()
    services = models.IntegerField()
    user_state = models.IntegerField()
    date_of_employment = models.DateField(verbose_name='Дата принятия на работу')
    date_of_dismissal = models.DateField(verbose_name='Дата принятия на работу')
    education = models.CharField(max_length=250, verbose_name='Образование')
    salary = models.IntegerField(verbose_name='Оклад')