# Generated by Django 5.1.5 on 2025-02-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('date_since', models.DateField(verbose_name='Дата начала периода')),
                ('date_to', models.DateField(verbose_name='Дата конца периода')),
            ],
        ),
    ]
