# Generated by Django 5.1.4 on 2025-02-04 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_name', models.CharField(max_length=250, verbose_name='last_name')),
                ('first_name', models.CharField(max_length=250, verbose_name='name')),
                ('patronymic', models.CharField(max_length=250, verbose_name='patronymic')),
                ('legal_adress', models.CharField(max_length=250, verbose_name='legal_adress')),
                ('physical_adress', models.CharField(max_length=250, verbose_name='physical_adress')),
                ('inn', models.IntegerField()),
                ('kpp', models.IntegerField()),
                ('bank', models.IntegerField()),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateTimeField()),
                ('passports_series', models.IntegerField()),
                ('passports_number', models.IntegerField()),
                ('services', models.IntegerField()),
                ('user_state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('price', models.IntegerField()),
                ('unit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('description', models.TextField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.clients')),
            ],
        ),
    ]
