# Generated by Django 5.1.5 on 2025-02-05 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clients'),
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
