# Generated by Django 5.1.5 on 2025-02-07 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('date_since', models.DateField(verbose_name='Дата начала периода')),
                ('date_to', models.DateField(verbose_name='Дата конца периода')),
                ('charts_data', models.CharField(max_length=250, verbose_name='Описание графика')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.subdivision', verbose_name='Подразделение')),
            ],
        ),
    ]
