# Generated by Django 5.1.5 on 2025-02-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank='True', verbose_name='Дата')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('unit', models.IntegerField(verbose_name='Единица измерения')),
            ],
        ),
    ]
