# Generated by Django 5.1.5 on 2025-02-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('price', models.IntegerField()),
                ('unit', models.IntegerField()),
            ],
        ),
    ]
