# Generated by Django 5.1.5 on 2025-02-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_date_alter_services_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateField(blank='True', verbose_name='Дата'),
        ),
    ]
